"""Default content for LawlerAI / Nancy Lawler site."""

DEFAULT_CONTENT = {
    "hero.tagline": "LawlerAI™ · Est. for Sports",
    "hero.headline_line1": "AI IS EASY TO USE.",
    "hero.headline_line2": "UNDERSTANDING ITS CONSEQUENCES IS NOT.",
    "hero.subheadline": "Across sports organizations, AI tools are being adopted quickly and informally. They promise speed, efficiency, and competitive advantage. What's harder to see is how everyday use compounds across teams, tools, data, and time.",
    "hero.cta_label": "Explore Your AI Exposure",
    "happening.headline_line1": "MOST ORGANIZATIONS DIDN'T SET OUT TO",
    "happening.headline_line2": '"ADOPT AI." THEY SIMPLY STARTED USING IT.',
    "happening.context": "Without shared visibility and accountability, AI use spreads faster than leadership can assess its impact.",
    "happening.closing_statement": "WITHOUT SHARED VISIBILITY AND ACCOUNTABILITY, AI USE SPREADS FASTER THAN LEADERSHIP CAN ASSESS ITS IMPACT.",
    "outcome.label": "The Outcome",
    "outcome.headline": "ORGANIZATIONS THAT\nUNDERSTAND THEIR AI\nEXPOSURE EARLY:",
    "outcome.benefit_1": "Move faster with confidence",
    "outcome.benefit_2": "Avoid downstream risk",
    "outcome.benefit_3": "Make better decisions over time",
    "outcome.tagline_1": "CONTROL DOESN'T SLOW YOU DOWN.",
    "outcome.tagline_2": "IT LETS YOU MOVE ON PURPOSE.",
    "clarity.label": "From Clarity to Strategy",
    "clarity.headline": "ONCE ORGANIZATIONS UNDERSTAND THEIR EXPOSURE, STRATEGY BECOMES POSSIBLE.",
    "clarity.intro": "LawlerAI helps leadership translate visibility into a clear AI strategy — developed inside your existing environment. This isn't a theoretical roadmap. It's a practical strategy grounded in your operating reality, governance posture, and business priorities.",
    "clarity.closing_tagline": "STRATEGY ISN'T ABOUT MOVING FASTER. IT'S ABOUT MOVING TOGETHER, WITH PURPOSE.",
    "cta.label": "Ready to Move Forward",
    "cta.headline_line1": "READY TO",
    "cta.headline_line2": "MOVE FORWARD.",
    "cta.subheadline": "LawlerAI helps sports organizations move forward with AI: deliberately, responsibly, and with eyes open.",
    "cta.button_label": "Explore Your AI Exposure",
    "footer.tagline": "Strategic AI Risk & Control for Sports Organizations",
    "footer.logo_url": "https://res.cloudinary.com/dcuswyfur/image/upload/v1772200535/logo_1_rayi6u.png",
    # Images (backgrounds, logos)
    "nav.logo_url": "https://res.cloudinary.com/dcuswyfur/image/upload/v1772196103/lawker_AI_Logo_jyfkkp.png",
    "hero.background_image": "",
    "hero.background_video_url": "https://www.youtube.com/embed/wzBf6Wm8na4?autoplay=1&mute=1&loop=1&playlist=wzBf6Wm8na4&controls=0&modestbranding=1&playsinline=1&rel=0",
    "cta.background_image": "",
    "cta.background_video_url": "https://www.youtube.com/embed/wzBf6Wm8na4?autoplay=1&mute=1&loop=1&playlist=wzBf6Wm8na4&controls=0&modestbranding=1&playsinline=1&rel=0",
    "built_for_sports.image_url": "https://res.cloudinary.com/dcuswyfur/image/upload/v1772177689/Nancy_svczvx.jpg",
    "site.title": "LawlerAI™ — Strategic AI Risk & Control for Sports Organizations",
    "site.meta_description": "Strategic AI Risk & Control for Sports Organizations. Understand your AI exposure. Move forward deliberately.",
}
