# Generated by Django 5.1.2 on 2026-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_where_ai_used', models.CharField(blank=True, max_length=100)),
                ('q2_confidence_level', models.CharField(blank=True, max_length=100)),
                ('q3_decision_maker', models.CharField(blank=True, max_length=100)),
                ('q4_who_knows', models.CharField(blank=True, max_length=100)),
                ('q5_policies', models.CharField(blank=True, max_length=100)),
                ('q6_risk_evaluation', models.CharField(blank=True, max_length=100)),
                ('q7_leadership_approach', models.CharField(blank=True, max_length=100)),
                ('q8_what_would_help', models.CharField(blank=True, max_length=100)),
                ('q9_biggest_concern', models.CharField(blank=True, max_length=100)),
                ('q10_additional_thoughts', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
